apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: queue-proxy
  description: Queue Proxy
  tags:
    - go
    - website
  annotations:
    github.com/project-slug: ka2222222/backstage
spec:
  type: website
  lifecycle: production
  owner: team-b
  system: podcast
